major refactoring
eeditiones/tuttle pull request #32
Opened 2023-09-30 15:38 UTC by line-o

fixes #14
fixes #18 

- Remove duplicate code
- make tuttle extensible to additional git services
- update node dependencies
- cleanup api code
- add unique operations (functions) for endpoints
- UI is now standards compliant and valid XHTML

2023-09-30 18:30 UTC, duncdrum requested changes
Looks very nice overall. Some small comments inline. 

Xar install needs fixing on ci

2023-09-30 18:30 UTC, duncdrum commented on src/index.html
> +                        <input type="text" autofocus="" autocomplete="false" />
Shouldn t this be `autofocus="autofocus"` ?

2023-09-30 18:30 UTC, duncdrum commented on src/modules/api.xql
>   : Trigger icremental update
Typo

2023-09-30 18:30 UTC, duncdrum commented on src/modules/config.xql
> +declare variable $config:tuttle-config as element(tuttle) := doc("/db/apps/tuttle/data/tuttle.xml")/tuttle;
`//tuttle` ? Might be more robust with older versions of exist

2023-09-30 18:30 UTC, duncdrum commented on src/modules/github.xql
> +        else if ($count > array:size($json)) (: raise error here? returns everything :)
Looks like a good place for throwing an error

2023-09-30 18:30 UTC, duncdrum commented on src/modules/gitlab.xql
> +        else if ($count > array:size($json)) (: raise error here? returns everything :)
S.a

2023-09-30 18:32 UTC, line-o commented on src/modules/api.xql
>   : Trigger icremental update
Well yes apparently not mine

2023-09-30 18:33 UTC, line-o commented on src/modules/config.xql
> +declare variable $config:tuttle-config as element(tuttle) := doc("/db/apps/tuttle/data/tuttle.xml")/tuttle;
I did not change the XPath so it will work as before

2023-09-30 18:34 UTC, line-o commented on src/modules/github.xql
> +        else if ($count > array:size($json)) (: raise error here? returns everything :)
Not necessarily. I just used 100 to hard-limit the size of returned elements. Think of a long commit history with thousands of commits.

2023-09-30 18:36 UTC, line-o commented
Ah now we are hit with localhost DNS resolution on Linux as well. Fun.

2023-10-01 07:10 UTC, line-o commented on src/index.html
> +                        <input type="text" autofocus="" autocomplete="false" />
`autofocus="false"` works too :)

2023-10-01 11:14 UTC, duncdrum commented
Nice. Should we adjust the sem-ver range in expath-pkg to excude exist v7, or is there something we can do about the failing tests and `:latest` ?

2023-10-02 10:39 UTC, line-o commented
@duncdrum  I have found and fixed a couple of more issues in the meantime. Please wait with merging.

2023-10-02 13:14 UTC, line-o commented on src/modules/github.xql
> +        else if ($count > array:size($json)) (: raise error here? returns everything :)
The function will now throw only for numbers smaller than 1.

2023-10-02 13:15 UTC, line-o commented on src/modules/gitlab.xql
> +        else if ($count > array:size($json)) (: raise error here? returns everything :)
This is intentionally not throwing.

2023-10-02 13:57 UTC, duncdrum reviewed
looks great, and thanks for adding the gitlab tests, good thinking batman.

sadly, `:latest` is still failing

2023-10-02 13:57 UTC, duncdrum commented on src/modules/github.xql
> +declare function github:incremental-dry($config as map(*)) {
missing return type?

2023-10-02 13:57 UTC, duncdrum commented on src/modules/github.xql
> +declare function github:incremental($config as map(*)) {
here too?

2023-10-02 13:57 UTC, duncdrum commented on src/modules/gitlab.xql
> +declare %private function gitlab:incremental-add($config as map(*), $files as xs:string*, $sha as xs:string) {
return type?

2023-10-02 14:20 UTC, line-o commented
Regarding processor version: changing the dependency to
```
  <dependency processor="http://exist-db.org" semver-min="5.5.1" semver-max="6" />
```
should do, but I think we should postpone this until we are about to release 2.0.0

2023-10-02 18:22 UTC, duncdrum commented
@line-o i m ok with that, but would prefer to at least mention the known incompatibility on the readme, in that case.

2023-10-02 18:44 UTC, line-o commented
It is worth to put that info somewhere. Since this is the case for the current release and main this can be done in a separate PR.

2023-10-04 07:04 UTC, JoernT approved these changes

2023-10-04 19:23 UTC, merged