next round of refactoring
eeditiones/tuttle pull request #35
Opened 2023-10-04 20:03 UTC by line-o

fixes #12

### Features

- Bump package version to 2.0.0 to reflect breaking changes and declare max processor version 6.x.x 
- rename `blacklist` to `ignore` in configuration and throughout the code 122981953eb1ce3d4797dfde9b162f2dd6f0b50c
- Backup tuttle configuration on deinstall and restore on installation if found. Will resort to commented example configuration if no backup is found. This is usually the case on clean installs. This feature has only been tested locally yet. But it's very reliable as my local testing workflow relied on it. cbeaa09030a10bc4f0a766dfdd8a542f4ce6c987
- A lot of behind the curtains optimisations to further reduce duplicated code.

### Fixes

- Module namespaces all start with `http://e-editiones.org`
- Tests have been adapted, improved and extended
- drop unused dependency on `shared-resources`

2023-10-05 21:26 UTC, duncdrum requested changes
Can we come up with something a bit more flexibel for the collection name of the backup files? some minor comments. All in all really good stuff. Can you also add a note on the readme about the v7 known incompatibility. We could now set `allow-fail` on CI for as long as we restrict installation on exist v7

2023-10-05 21:26 UTC, duncdrum commented on src/cleanup.xq
> +declare variable $backup-collection := "/db/tuttle-backup/";
see my comment on mattermost, I d really prefer a collection name that is more flexible for other apps as well, and won't lead to one collection per app with similar demands. so far we only have `system` and `app` following the `db` root collection. Lets create a third location for this kind of backup files

2023-10-05 21:26 UTC, duncdrum commented on src/modules/api.xql
>   : Deploy  Repo
could you disambiguate that a bit, deploy could mean many things, deploy release artifact, publish to GitHub/Gitlab, deploy repo to public repo, deploy to existed instance, …?

2023-10-05 21:26 UTC, duncdrum commented on src/modules/api.xql
> +                let $errors := some $a in ($incremental?new?*, $incremental?del?*)?2 satisfies not($a)
lovely, but it might benefit from an inline comment, explaining what's going on

2023-10-05 21:26 UTC, duncdrum commented on src/modules/app.xql
> + : $base the absolute DB path to a collection. Assumes no slash at the end
Can you add `@param` for proper xqdoc syntax

2023-10-05 21:30 UTC, line-o commented on src/modules/app.xql
> + : $base the absolute DB path to a collection. Assumes no slash at the end
I will not start making all the comment-blocks proper XQdoc, since this would be the first one.

2023-10-05 21:31 UTC, line-o commented on src/modules/app.xql
> + : $base the absolute DB path to a collection. Assumes no slash at the end
I would prefer if they are but this is not the case at the moment. It would make a perfect, separate PR.

2023-10-05 21:35 UTC, line-o commented on src/cleanup.xq
> +declare variable $backup-collection := "/db/tuttle-backup/";
I do favour a broader solution as well. Please understand that this is not the right moment to set de-facto standards and the collection in this case is very short-lived. The entire `/db/tuttle-backup` is removed after installation.
And I would also prefer to discuss a general solution within the community not just among us.

2023-10-05 21:36 UTC, duncdrum commented on src/modules/app.xql
> + : $base the absolute DB path to a collection. Assumes no slash at the end
but this is a comment block you authored no? what's the harm in fixing new stuff. I agree that going over all xqdoc like but no quite comments is something for a separate PR

2023-10-05 21:39 UTC, line-o commented
@duncdrum Please be aware that there are much much more pressing issues than comments. We will get to those eventually. But those do not pose risks when running in production.

2023-10-05 21:43 UTC, line-o commented on src/modules/app.xql
> + : $base the absolute DB path to a collection. Assumes no slash at the end
I see that you read my comment as a broken xqdoc. This was not intentional. :)

2023-10-05 21:44 UTC, duncdrum commented on src/cleanup.xq
> +declare variable $backup-collection := "/db/tuttle-backup/";
happy to discuss a general solution with the community. I just don't see what we gain there, by adopting a single use solution now, instead of one that is open to extension

2023-10-05 22:52 UTC, line-o commented on src/modules/api.xql
>   : Deploy  Repo
done

2023-10-05 22:52 UTC, line-o commented on src/modules/api.xql
> +                let $errors := some $a in ($incremental?new?*, $incremental?del?*)?2 satisfies not($a)
should be clearer now ... `$a` was also a poor choice for a variable name.

2023-10-05 22:53 UTC, line-o commented on src/modules/app.xql
> + : $base the absolute DB path to a collection. Assumes no slash at the end
It's the first valid XQdoc block now 🎉

2023-10-05 22:55 UTC, line-o commented on src/cleanup.xq
> +declare variable $backup-collection := "/db/tuttle-backup/";
If we choose a collection name that is
a) the one other apps will be using then it needs extra protection from removal and will have to stay there even if unused
b) not the one we are choosing here, the code has to be changed anyway

2023-10-06 06:30 UTC, duncdrum approved these changes

2023-10-06 09:43 UTC, line-o commented on src/controller.xql
> +else if ($is-get and $exist:path eq "/api.html" or $exist:path eq "/api.json") then
This route is still problematic as it allows POST and PUT requests to api.json

2023-10-12 10:54 UTC, merged